language: java
script: mvn test
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - TRAVIS=true
before_install:
  - 'export TRAVIS=true'
  # start your web application and listen on `localhost`
  #  https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - 'google-chrome-stable --headless --remote-debugging-port=9222 --disable-gpu http://localhost &'
jdk:
  - oraclejdk8
notifications:
  email:
    on_success: never
    on_failure: change

